#  Name of workflow
name: Deploy workflow

# When workflow is triggered
on:
  push:
    branches:
      - main

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Deploy to github
      