[build-system]
requires = [
    "setuptools>=42",
    "wheel"
    "click==7.1.2",
    "pyfiglet==0.7",
    "PyInquirer==1.0.3",
    "requests==2.25.1",
    "selenium== 3.141.0",
    "bs4==0.0.1",
    "chromedriver-py==92.0.4515.43",
]
build-backend = "setuptools.build_meta"