name: 'publish'
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build binary wheel and a source tarball
        run: python publish.py bdist_wheel

